name: language_learning_app
description: A comprehensive Turkish language learning application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # Audio & Media
  audioplayers: ^5.2.1
  # speech_to_text: ^6.6.0  # Commented out temporarily due to build issues
  permission_handler: ^11.0.1

  # State Management
  provider: ^6.1.1

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # HTTP & Network
  http: ^1.1.0
  dio: ^5.4.0

  # Utils
  shared_preferences: ^2.2.2
  uuid: ^4.2.1

  # Navigation
  go_router: ^12.1.3

  # Animations
  lottie: ^2.7.0

  # File handling
  image_picker: ^1.0.5

  # Charts & Progress
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Remove asset references for now since directories don't exist
  # assets:
  #   - assets/images/
  #   - assets/audio/
  #   - assets/animations/
  #   - assets/icons/

  # Remove font references for now since files don't exist
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700